import type { RegisterForm } from "./interfaces";
import { Cliente } from "./interfaces";
import type { BaseProduct } from "./interfaces";
export declare function getRegisteredUsers(): RegisterForm[];
export declare function showUsersAllUsers(): void;
export declare function cleanSection(sectionId: string): void;
export declare function showUsers(): void;
export declare function cleanOldUsers(): void;
export declare function changeTextContent(elementId: string, text: string): void;
export declare function showPopUp(title: string, message: string): void;
export declare function addCloseButton(containerId: string): void;
export declare function showPopUpSelection(title: string, message: string, checkright: string, checkleft: string): void;
export declare function ValidationNewUser(): boolean;
export declare function checkPassword(user: RegisterForm): false | undefined;
export declare function checkRegistration(): void;
export declare function checkReservedLogin(): void;
export declare function checkUserLogin(): string | undefined;
export declare function disableDropdown(dropdownId: string, bool: boolean): void;
export declare function showHidden(subMenuId: string): void;
export declare function genderMenu(valueDropdown: string): void;
export declare function checkInputQuantity(): number | null;
export declare function checkPrizeInput(): number | null;
export declare function checkDescriptionInput(): string | null;
export declare function checkInputImage(): string | null;
export declare function insertProduct(productData: BaseProduct): Promise<void>;
export declare function createTable(products: BaseProduct[]): void;
export declare function checkedFilterShop(check: HTMLElement, allElement: NodeListOf<HTMLElement>): string | "";
export declare function checkColorCardShop(products: BaseProduct[], target: HTMLInputElement, clone: HTMLElement): string | "";
export declare function setSUmTotCart(products: ReturnType<Cliente['getDetailedCart']>): void;
//# sourceMappingURL=dom.d.ts.map